services:
  baronette-data-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: baronette-data-api
    container_name: baronette-data-api
    volumes:
      - ./src:/home/docker/baronette/data-api/app/src
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - baronette_db_api_network
      - baronette-webapp-api-network
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.baronettewebapi.rule=Host(`baronettewebapi.localhost`)"
      - "traefik.http.routers.baronettewebapi.entrypoints=websecure"
      - "traefik.http.routers.baronettewebapi.tls=true"
      - "traefik.http.services.baronettewebapi.loadbalancer.server.port=3000"

networks:
  baronette_db_api_network:
    external: true
  baronette-webapp-api-network:
    external: true
  traefik:
    external: true