services:
  baronette-data-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: baronette-data-api
    container_name: baronette-data-api
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/app/src
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - baronette_db_api_network
      - baronette-webapp-api-network
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"
      - "traefik.http.routers.bwapi.rule=Host(`bwapi.baronette.es`)"
      - "traefik.http.routers.bwapi.entrypoints=websecure"
      - "traefik.http.routers.bwapi.tls=true"
      - "traefik.http.services.bwapi.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.bwapi-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.bwapi.middlewares=bwapi-stripprefix"


networks:
  baronette_db_api_network:
    external: true
  baronette-webapp-api-network:
    external: true
  traefik-net:
    external: true
